Fixes sanity tests
The sanity tests are failing with the following error:

exec /whereabouts version
error: enter: cannot provide -v/--verbose before "exec" subcommand

Pebble was recently updated, no longer allowing exec after --verbose
(which is in the entrypoint).

This fixes the sanity tests by using the --entrypoint docker run
parameter.